### ISSUE TITLE
XtremIO Certificate : Access Denied

### ISSUE THREAD

**Issue by hroman73** [bkvarda/xtremlib#1]
I've tried your steps and unfortunately I'm unable to get past this error when interfacing with my XtremIO from within my Windows 2012 R2 server.

"Error: XtremIO name or IP not resolveable. It may have been mistyped. This may also indicate that you have not properly imported the XtremIO certificate."

I know the ip address, username and passwords are correct...so that leave the certificate, which I've never had to do for powershell to work correctly before.

Regards...

**Comment by bkvarda** [comment]
Unfortunately this will not work unless you import the certificate. The certificate is needed to issue a secure web request with the XMS using the underlying Invoke-RestMethod cmdlet, and for better or for worse the certificate exchange logic is not handled by the module.
