### ISSUE TITLE
Refresh Issue

### ISSUE THREAD

**Issue by rpuertas** [bkvarda/xtremlib#4]
I’m trying run the information published on your blog about of refresh using powershell, I have configured this and I can see some information using the command get and create volumes using the command new volume.

https://github.com/bkvarda/xtremlib
I want do refresh, but I have received the following error

Custer is available:
PS C:\temp\xtremlib> Get-XtremClusters

href                                                        name

---

https://10.28.64.40/api/json/v2/types/clusters/1            XtremIO-6
###### 

PS C:\temp\xtremlib> New-XtremSnapshotRefresh -ParentType from-consistency-group-id -ParentName test -RefreshType to-snapshot-set-id -RefreshName test -NewName test2
sys_not_found
message                                                                                                      error_code

---

sys_not_found                                                                                                       400

The CG Name is test
The snapshots Name is test
I want refresh from consistency group to snapshots

**Comment by bkvarda** [comment]
Sorry for the delayed response. I have not maintained this project for quite some time, and wouldn't have a system to test against any longer even if I was maintaining it. I believe EMC has a powershell tool that does this now (might be ESI?)
